### ISSUE TITLE
Various compile errors with example

### ISSUE THREAD

**Issue by xgdgsc** [marketplacer/swift-badge#1]
swift-badge-master/swift-badge/SwiftBadge.swift:15:12: Initializer does not override a designated initializer from its superclass

swift-badge-master/swift-badge/SwiftBadge.swift:16:5: Must call a designated initializer of the superclass 'UILabel'

swift-badge-master/swift-badge/ViewController.swift:50:12: 'NSString' is not implicitly convertible to 'String'; did you mean to use 'as' to explicitly convert?

I' m using latest Xcode and swift.

**Comment by evgenyneu** [comment]
Hi, @xgdgsc, thanks for the feedback. I have updated the repository for Xcode 7 and Swift 2.0.

**Comment by xgdgsc** [comment]
swift-badge-master/swift-badge/SwiftBadge.swift:32:47: Cannot assign to 'translatesAutoresizingMaskIntoConstraints' in 'self'

the previous setTranslatesAutoresizingMaskIntoConstraints(false) works.

**Comment by evgenyneu** [comment]
Oops, sorry @xgdgsc, I misunderstood you, I thought you were using swift 2.0 and Xcode 7 so I updated to it. It looks like you are using Xcode 6?

**Comment by xgdgsc** [comment]
Yes, 6.

**Comment by evgenyneu** [comment]
Cool, I should have asked. I have created an [xcode 6 branch](https://github.com/exchangegroup/swift-badge/tree/xcode6) for you. The only difference is that `setTranslatesAutoresizingMaskIntoConstraints` line that you mentioned. Thanks. 🌷
