### ISSUE TITLE
[Bug] Top left stroke edge error

### ISSUE THREAD

**Issue by gperdomor** [marketplacer/swift-badge#11]
The corner radius support will be added in #10, but if the radius is 0, and the label has border, the top left border has an error

![screen shot 2016-11-09 at 10 49 37 am](https://cloud.githubusercontent.com/assets/371939/20140488/3fbf7b0a-a66a-11e6-87d5-01d02e9d323a.png)

Without border: 
![screen shot 2016-11-09 at 10 50 56 am](https://cloud.githubusercontent.com/assets/371939/20140524/68ed25c2-a66a-11e6-9188-650d10d0d3cd.png)

**Comment by evgenyneu** [comment]
Hi @gperdomor, this is fixed now, used a rectangular bath when the corner radius is zero. Thanks again for your help. All the best.
