### ISSUE TITLE
What version is in Swift 2.3?

### ISSUE THREAD

**Issue by uknowmeright** [marketplacer/swift-badge#12]
I am having trouble finding what Version supports swift 2.3?

I have gone as fat back as 2.011. Could you include this in the docs for future reference?

Thanks!

**Comment by evgenyneu** [comment]
Hi, @uknowmeright, I am sorry, there is no Swift 2.3 version of the library, unfortunately.

**Comment by evgenyneu** [comment]
Closing the issue. Feel free to reopen if needed.
