### ISSUE TITLE
Subclassing when using CocoaPods

### ISSUE THREAD

**Issue by r-dent** [marketplacer/swift-badge#13]
Hi!

I wanted to subclass BadgeSwift to add some custom default styling. But when i tried i got..

> Cannot inherit from non-open class 'BadgeSwift' outside of it´s defining module.

I´m using CocoaPods. I guess this is just because of the missing `open` declaration. 
Could we add this? Or is the class intentionally non-open?

**Comment by evgenyneu** [comment]
Hi @r-dent, changed the methods to `open` in version 5. Thanks for your feedback!

**Comment by evgenyneu** [comment]
Closing the issue. Feel free to reopen if needed.
