### ISSUE TITLE
I can't import BadgeSwift

### ISSUE THREAD

**Issue by ArtaMoaser** [marketplacer/swift-badge#16]
when in try to use swift-badge I can't import BadgeSwift
I installed  pod but I can't import it 

* Xcode version : 9.0.1.

**Comment by evgenyneu** [comment]
Hi @ArtaMoaser, thanks for reporting. 

1. Which method did you use to install BadgeSwift (manual, CocoaPods, Carthage)?
2. What do you mean by "I can't import BadgeSwift", sorry?

**Comment by ArtaMoaser** [comment]
I use CocoaPods and when I import BadgeSwit I get "Cannot load underlying module for 'BadgeSwift'" error!

**Comment by evgenyneu** [comment]
Thanks, sorry what do you mean by "when I import BadgeSwit"? How do you import it?

**Comment by ArtaMoaser** [comment]
I install with the pod, after that, I drag and drop a label in viewController and I set  "BadgeSwift" in "custom class" of the label ( It works! ) after that I try to add "Import BadgeSwift " such as the example "swift-badge/Demo-iOS/ViewControllers/CreateBadgeFromCodeViewController.swift"
In First line you added "import BadgeSwift" when I added it, I got the error "Cannot load underlying module for 'BadgeSwift"

**Comment by evgenyneu** [comment]
I could not reproduce your problem in Xcode: 9.0. I've created a new demo project, added the library through CocoaPods and wrote `import BadgeSwift` at the top of the file. It compiled without any errors. Please see the demo project attached. Let me know how it goes.

[DemoSwiftBadge.zip](https://github.com/evgenyneu/swift-badge/files/1484364/DemoSwiftBadge.zip)

**Comment by evgenyneu** [comment]
I could reproduce your problem in Xcode 9.1. I fixed it by installing the latest CocoaPods (`gem install cocoapods --pre`) and running `pod install`. Let me know if it works for you. My current CocoaPods version is 1.4.0.beta.2.

**Comment by ArtaMoaser** [comment]
I downloaded Demo file and runned it and it's worked after but show "No such module 'BadgeSwift'" ( see the image ) after that I switch to my project and, It works now...I don't know how, but without any reason, it working! 
Thank you for your help
<img width="757" alt="screen shot 1396-08-28 at 10 28 18" src="https://user-images.githubusercontent.com/23609854/32988251-69f5104c-cd15-11e7-841f-0405ba3ac18b.png">

**Comment by evgenyneu** [comment]
No worries, I'm glad it worked.
