### ISSUE TITLE
error line

### ISSUE THREAD

**Issue by longxianlin** [marketplacer/swift-badge#2]
translatesAutoresizingMaskIntoConstraints = false

**Comment by evgenyneu** [comment]
Thanks for reporting, the master branch is currently written for Xcode 7 / Swift 2.0. 
There is an `xcode6` branch: https://github.com/exchangegroup/swift-badge/blob/xcode6/swift-badge/SwiftBadge.swift

Or you can manually change that line to this to make it run in Xcode 6.

``` swift
setTranslatesAutoresizingMaskIntoConstraints(false)
```

**Comment by evgenyneu** [comment]
@longxianlin let me know if you have any issues. Thanks.
