### ISSUE TITLE
The small red part

### ISSUE THREAD

**Issue by elibooklover** [marketplacer/swift-badge#20]
Please consider submitting the following information (if relevant):

* Library setup method: CocoaPods.
* Version of the library. Example: 5.0.1.
* Xcode version. Example: 9.4.1.
* OS version. Example: iOS 11.4.

The small red part that appears to be cut off on the top right always pops up. What should I do in order to remove it?

![img_2880](https://user-images.githubusercontent.com/32969240/42321968-91f01bc6-8095-11e8-97b7-7ff5e270c61f.jpg)

Thank you!

**Comment by evgenyneu** [comment]
Thanks for reporting @elibooklover. This is really weird, I've never seen such thing before. I don't know what is causing it. Do you think you can make a simple demo app that recreates this bug and attach it here? So I can have a look?

**Comment by elibooklover** [comment]
Thanks for your comments. I figured out why it happened. I added the badge by using both codes and the label. Since I removed the label, it disappeared. Thanks!

**Comment by evgenyneu** [comment]
I'm glad you figured it out! 👍
