### ISSUE TITLE
Swift 4.2

### ISSUE THREAD

**Issue by wolfAle** [marketplacer/swift-badge#21]
Hi,

I'm using the last version of the library from cocoapods (BadgeSwift (5.0.1)) and it doesn't build on Swift4.2.
Is there any plan to update it? 
It's just one line of code actually:
`let rectWithoutInsets = UIEdgeInsetsInsetRect(rect, insets)`
to
`let rectWithoutInsets = rect.inset(by: insets)`

Thanks,

**Comment by evgenyneu** [comment]
Thanks for reminding! Version 6 now supports Swift 4.2.

**Comment by wolfAle** [comment]
Great, thanks, it works now!
