### ISSUE TITLE
CocoaPods BadgeSwift v6.0 is not found

### ISSUE THREAD

**Issue by kuoliangkwong** [marketplacer/swift-badge#22]
* Library setup method: CocoaPods
* Version of the library. 6.0.
* Xcode version. 10.0
* OS version. iOS 12.0

**Comment by evgenyneu** [comment]
Thanks for reporting, @kuoliangkwong. Can you explain the problem and supply the error message please, if there is one? I'm not quite sure what you mean. :)

**Comment by kuoliangkwong** [comment]
I got this error when pod install BadgeSwift v6.0
```
[!] CocoaPods could not find compatible versions for pod "BadgeSwift":
  In Podfile:
    BadgeSwift (~> 6.0)
```

The latest version I can get is v5.0.1

**Comment by evgenyneu** [comment]
Hmm, that's weird. Is it the entire error message? Does it say what it means by "compatible versions"? I've also found [this discussion](https://stackoverflow.com/questions/48638059/could-not-find-compatible-versions-for-pod) on stackoverflow that might be relevant.

**Comment by kuoliangkwong** [comment]
Hmm i tried again, and it seems working now. What I did is pod update and pod install again. Did u change anything at ur end?

**Comment by evgenyneu** [comment]
I'm glad that it's working now. I did not make any changes to the repository for the last two weeks.

**Comment by kuoliangkwong** [comment]
Seems odd~ I didn't do anything from my end either haha. Glad it's working now too. I'll proceed close this issue
