### ISSUE TITLE
ld: warning: linking against a dylib which is not safe for use in application extensions

### ISSUE THREAD

**Issue by acecilia** [marketplacer/swift-badge#23]
As explained [here](https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/ExtensionOverview.html#//apple_ref/doc/uid/TP40014214-CH2-SW6), there are some APIs unavailable for extensions. Seems like BadgeSwift is using them, because I am getting the error:

`ld: warning: linking against a dylib which is not safe for use in application extensions`

Any idea which is the part of the code that is using this kind of APIs? Looking at the functionality of this framework, it should be possible to use it in extensions.

**Comment by evgenyneu** [comment]
Hello @acecilia, thanks for reporting.

> Any idea which is the part of the code that is using this kind of APIs?

No idea, sorry.

> Looking at the functionality of this framework, it should be possible to use it in extensions.

Yes, I'm not sure if we are using any restricted APIs here. 

I found an issue that may be similar to yours [reported here](https://github.com/bugsnag/bugsnag-cocoa/issues/140). Please let me know if any of the solutions help.

**Comment by acecilia** [comment]
@evgenyneu there should be something that is not safe for extensions, but I have been looking into the code and I can not find what. For example, in PureLayout they have a special macro to enable when using it in extensions, so they avoid using `UIApplication`: https://github.com/PureLayout/PureLayout/wiki/App-Extensions
<img width="746" alt="screen shot 2018-10-18 at 02 10 02" src="https://user-images.githubusercontent.com/7938671/47123309-fef34900-d27a-11e8-8bfb-6abf824afb12.png">

I am using Carthage, so the problem and solution they explain in the link you passed to me I think they are not related to this.

**Comment by evgenyneu** [comment]
I see, is there a way for me to check which type/classes am I using that are causing this warning? I tried to set the "Require Only App-Extension-Safe API" option to "Yes" and rebuild the library, but the Xcode did not give me any warnings. Maybe it's worth to ask Carthage people?

**Comment by acecilia** [comment]
@evgenyneu I managed to fix it, the solution is what you tried, but the warning does not appear if you are not working in an extension. I can confirm that with the fix in https://github.com/evgenyneu/swift-badge/pull/24 the warning goes away

**Comment by evgenyneu** [comment]
Thanks for the fix, @acecilia!
