### ISSUE TITLE
.Hidden

### ISSUE THREAD

**Issue by uknowmeright** [marketplacer/swift-badge#4]
The .hidden property on the badge seems to hide only the red background. The white text still remains visible. I have tried setting it to "" but it remains the previous value. Any ideas? Thanks

```
if listingsToLoad[indexPath.row].unReadMessages.value != nil {
    cell.cellBadge.hidden = false
    cell.cellBadge.text = String(listingsToLoad[indexPath.row].unReadMessages.value!)
} else {
    cell.cellBadge.hidden = true
    cell.cellBadge.text = ""
}
```

**Comment by evgenyneu** [comment]
This is weird indeed, it should hide the text as well. The `SwiftBadge` is a subclass of `UILabel`. Try using a UILabel instead and see if gets hidden when you set its `hidden` property to true.

**Comment by uknowmeright** [comment]
It does hide it if its a UILabel. Must be something in the Class? I cant figure out what though.

**Comment by evgenyneu** [comment]
No idea, sorry.

**Comment by amg1976** [comment]
Hi @uknowmeright, I believe that when the PR I made is reviewed and approved (sorry @evgenyneu for taking so long to update it) this issue will no longer exist. I made a simple test, hiding the badge when the cell is selected and it worked.

**Comment by evgenyneu** [comment]
Thanks, @amg1976, I think you fixed the issue. Here is a demo app.
[UsingSwiftBadge.zip](https://github.com/marketplacer/swift-badge/files/158373/UsingSwiftBadge.zip)

**Comment by evgenyneu** [comment]
Closing the issue, feel free to reopen if needed.
