### ISSUE TITLE
Swift 2.2 support

### ISSUE THREAD

**Issue by leonereveel** [marketplacer/swift-badge#6]
Do you have an version for Swift 2.2?

**Comment by evgenyneu** [comment]
Hi @leonereveel, yes it is a file-only setup for Swift 2.2. See the details here and let me know how it goes.

https://github.com/marketplacer/swift-badge/wiki/Legacy-Swift-versions

**Comment by evgenyneu** [comment]
Closing the issue, feel free to reopen if needed.
