### ISSUE TITLE
well...its cant use in swift2.x

### ISSUE THREAD

**Issue by ARonDellon** [marketplacer/swift-badge#7]
many syntax was not exist...sad about this

**Comment by evgenyneu** [comment]
Hello @ARonDellon, thank for your feedback. If you need to use the library in previous versions of Swift you can check the setup instructions here:

https://github.com/marketplacer/swift-badge/wiki/Legacy-Swift-versions 

Let me know how it goes.

**Comment by ARonDellon** [comment]
@evgenyneu wow ,it works well . thx a lot

**Comment by evgenyneu** [comment]
No worries,  all the best.
